name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'AibinuolaDamilola/ai-security-defense-lab'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "fellowship@cyberdefense.com"
          git config --global user.name "AibinuolaDamilola"
          git push --force https://user:$HF_TOKEN@huggingface.co/spaces/cyberdammy/ai-security-defense-lab main
